plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    id("io.genstrings.plugin")
}

android {
    namespace = "io.genstrings.languagechecker"
    compileSdk = 35
    defaultConfig {
        minSdk = 26
        targetSdk = 35

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    androidTestImplementation(libs.test.junit.ext)
    androidTestImplementation(libs.test.runner)
}

genstrings {
    languages {
        // generated via LanguageChecker.printLanguageDirectives() on Emulator with API 36
        create("af") { description = "Afrikaans" }
        create("agq") { description = "Aghem" }
        create("ak") { description = "Akan" }
        create("am") { description = "Amharic" }
        create("ar") { description = "Arabic" }
        create("as") { description = "Assamese" }
        create("asa") { description = "Asu" }
        create("ast") { description = "Asturian" }
        create("b+az+Cyrl") { description = "Azerbaijani (Cyrillic)" }
        create("b+az+Latn") { description = "Azerbaijani (Latin)" }
        create("bas") { description = "Basaa" }
        create("be") { description = "Belarusian" }
        create("bem") { description = "Bemba" }
        create("bez") { description = "Bena" }
        create("bg") { description = "Bulgarian" }
        create("bgc") { description = "Haryanvi" }
        create("bho") { description = "Bhojpuri" }
        create("blo") { description = "Anii" }
        create("bm") { description = "Bambara" }
        create("bn") { description = "Bangla" }
        create("bo") { description = "Tibetan" }
        create("br") { description = "Breton" }
        create("brx") { description = "Bodo" }
        create("b+bs+Cyrl") { description = "Bosnian (Cyrillic)" }
        create("b+bs+Latn") { description = "Bosnian (Latin)" }
        create("ca") { description = "Catalan" }
        create("ccp") { description = "Chakma" }
        create("ce") { description = "Chechen" }
        create("ceb") { description = "Cebuano" }
        create("cgg") { description = "Chiga" }
        create("chr") { description = "Cherokee" }
        create("ckb") { description = "Central Kurdish" }
        create("cs") { description = "Czech" }
        create("csw") { description = "Swampy Cree" }
        create("cv") { description = "Chuvash" }
        create("cy") { description = "Welsh" }
        create("da") { description = "Danish" }
        create("dav") { description = "Taita" }
        create("de") { description = "German" }
        create("dje") { description = "Zarma" }
        create("doi") { description = "Dogri" }
        create("dsb") { description = "Lower Sorbian" }
        create("dua") { description = "Duala" }
        create("dyo") { description = "Jola-Fonyi" }
        create("dz") { description = "Dzongkha" }
        create("ebu") { description = "Embu" }
        create("ee") { description = "Ewe" }
        create("el") { description = "Greek" }
        create("eo") { description = "Esperanto" }
        create("es") { description = "Spanish" }
        create("et") { description = "Estonian" }
        create("eu") { description = "Basque" }
        create("ewo") { description = "Ewondo" }
        create("fa") { description = "Persian" }
        create("b+ff+Adlm") { description = "Fula (Adlam)" }
        create("b+ff+Latn") { description = "Fula (Latin)" }
        create("fi") { description = "Finnish" }
        create("fil") { description = "Filipino" }
        create("fo") { description = "Faroese" }
        create("fr") { description = "French" }
        create("fur") { description = "Friulian" }
        create("fy") { description = "Western Frisian" }
        create("ga") { description = "Irish" }
        create("gaa") { description = "Ga" }
        create("gd") { description = "Scottish Gaelic" }
        create("gl") { description = "Galician" }
        create("gsw") { description = "Swiss German" }
        create("gu") { description = "Gujarati" }
        create("guz") { description = "Gusii" }
        create("gv") { description = "Manx" }
        create("ha") { description = "Hausa" }
        create("haw") { description = "Hawaiian" }
        create("he") { description = "Hebrew" } // alias to "iw" (API 26)
        create("hi") { description = "Hindi" }  // may need alias to b+hi+Latn on API 36?
        create("hr") { description = "Croatian" }
        create("hsb") { description = "Upper Sorbian" }
        create("hu") { description = "Hungarian" }
        create("hy") { description = "Armenian" }
        create("ia") { description = "Interlingua" }
        create("id") { description = "Indonesian" } // alias to "in" (API 26)
        create("ie") { description = "Interlingue" }
        create("ig") { description = "Igbo" }
        create("ii") { description = "Sichuan Yi" }
        create("is") { description = "Icelandic" }
        create("it") { description = "Italian" }
        create("ja") { description = "Japanese" }
        create("jgo") { description = "Ngomba" }
        create("jmc") { description = "Machame" }
        create("jv") { description = "Javanese" }
        create("ka") { description = "Georgian" }
        create("kab") { description = "Kabyle" }
        create("kam") { description = "Kamba" }
        create("kde") { description = "Makonde" }
        create("kea") { description = "Kabuverdianu" }
        create("kgp") { description = "Kaingang" }
        create("khq") { description = "Koyra Chiini" }
        create("ki") { description = "Kikuyu" }
        create("kk") { description = "Kazakh (Cyrillic)" }
        create("kkj") { description = "Kako" }
        create("kl") { description = "Kalaallisut" }
        create("kln") { description = "Kalenjin" }
        create("km") { description = "Khmer" }
        create("kn") { description = "Kannada" }
        create("ko") { description = "Korean" }
        create("b+kok+Deva") { description = "Konkani (Devanagari)" }
        create("b+kok+Latn") { description = "Konkani (Latin)" }
        create("b+ks+Arab") { description = "Kashmiri (Arabic)" }
        create("b+ks+Deva") { description = "Kashmiri (Devanagari)" }
        create("ksb") { description = "Shambala" }
        create("ksf") { description = "Bafia" }
        create("ksh") { description = "Colognian" }
        create("ku") { description = "Kurdish" }
        create("kw") { description = "Cornish" }
        create("b+kxv+Deva") { description = "Kuvi (Devanagari)" }
        create("b+kxv+Latn") { description = "Kuvi (Latin)" }
        create("b+kxv+Orya") { description = "Kuvi (Odia)" }
        create("b+kxv+Telu") { description = "Kuvi (Telugu)" }
        create("ky") { description = "Kyrgyz" }
        create("lag") { description = "Langi" }
        create("lb") { description = "Luxembourgish" }
        create("lg") { description = "Ganda" }
        create("lij") { description = "Ligurian" }
        create("lkt") { description = "Lakota" }
        create("lmo") { description = "Lombard" }
        create("ln") { description = "Lingala" }
        create("lo") { description = "Lao" }
        create("lrc") { description = "Northern Luri" }
        create("lt") { description = "Lithuanian" }
        create("lu") { description = "Luba-Katanga" }
        create("luo") { description = "Luo" }
        create("luy") { description = "Luyia" }
        create("lv") { description = "Latvian" }
        create("mai") { description = "Maithili" }
        create("mas") { description = "Masai" }
        create("mer") { description = "Meru" }
        create("mfe") { description = "Morisyen" }
        create("mg") { description = "Malagasy" }
        create("mgh") { description = "Makhuwa-Meetto" }
        create("mgo") { description = "Metaʼ" }
        create("mi") { description = "Māori" }
        create("mk") { description = "Macedonian" }
        create("ml") { description = "Malayalam" }
        create("mn") { description = "Mongolian" }
        create("mni") { description = "Manipuri (Bangla)" }
        create("mr") { description = "Marathi" }
        create("ms") { description = "Malay" }
        create("mt") { description = "Maltese" }
        create("mua") { description = "Mundang" }
        create("my") { description = "Burmese" }
        create("mzn") { description = "Mazanderani" }
        create("naq") { description = "Nama" }
        create("nb") { description = "Norwegian Bokmål" }
        create("nd") { description = "North Ndebele" }
        create("nds") { description = "Low German" }
        create("ne") { description = "Nepali" }
        create("nl") { description = "Dutch" }
        create("nmg") { description = "Kwasio" }
        create("nn") { description = "Norwegian Nynorsk" }
        create("nnh") { description = "Ngiemboon" }
        create("no") { description = "Norwegian" }
        create("nqo") { description = "N’Ko" }
        create("nso") { description = "Northern Sotho" }
        create("nus") { description = "Nuer" }
        create("nyn") { description = "Nyankole" }
        create("oc") { description = "Occitan" }
        create("om") { description = "Oromo" }
        create("or") { description = "Odia" }
        create("os") { description = "Ossetic" }
        create("b+pa+Arab") { description = "Punjabi (Arabic)" }
        create("b+pa+Guru") { description = "Punjabi (Gurmukhi)" }
        create("pcm") { description = "Nigerian Pidgin" }
        create("pl") { description = "Polish" }
        create("prg") { description = "Prussian" }
        create("ps") { description = "Pashto" }
        create("pt") { description = "Portuguese" }
        create("qu") { description = "Quechua" }
        create("raj") { description = "Rajasthani" }
        create("rm") { description = "Romansh" }
        create("rn") { description = "Rundi" }
        create("ro") { description = "Romanian" }
        create("rof") { description = "Rombo" }
        create("ru") { description = "Russian" }
        create("rw") { description = "Kinyarwanda" }
        create("rwk") { description = "Rwa" }
        create("sa") { description = "Sanskrit" }
        create("sah") { description = "Yakut" }
        create("saq") { description = "Samburu" }
        create("sat") { description = "Santali (Ol Chiki)" }
        create("sbp") { description = "Sangu" }
        create("sc") { description = "Sardinian" }
        create("b+sd+Arab") { description = "Sindhi (Arabic)" }
        create("b+sd+Deva") { description = "Sindhi (Devanagari)" }
        create("se") { description = "Northern Sami" }
        create("seh") { description = "Sena" }
        create("ses") { description = "Koyraboro Senni" }
        create("sg") { description = "Sango" }
        create("b+shi+Latn") { description = "Tachelhit (Latin)" }
        create("b+shi+Tfng") { description = "Tachelhit (Tifinagh)" }
        create("si") { description = "Sinhala" }
        create("sk") { description = "Slovak" }
        create("sl") { description = "Slovenian" }
        create("smn") { description = "Inari Sami" }
        create("sn") { description = "Shona" }
        create("so") { description = "Somali" }
        create("sq") { description = "Albanian" }
        create("b+sr+Cyrl") { description = "Serbian (Cyrillic)" }
        create("b+sr+Latn") { description = "Serbian (Latin)" }
        create("st") { description = "Southern Sotho" }
        create("su") { description = "Sundanese (Latin)" }
        create("sv") { description = "Swedish" }
        create("sw") { description = "Swahili" }
        create("syr") { description = "Syriac" }
        create("szl") { description = "Silesian" }
        create("ta") { description = "Tamil" }
        create("te") { description = "Telugu" }
        create("teo") { description = "Teso" }
        create("tg") { description = "Tajik" }
        create("th") { description = "Thai" }
        create("ti") { description = "Tigrinya" }
        create("tk") { description = "Turkmen" }
        create("tn") { description = "Tswana" }
        create("to") { description = "Tongan" }
        create("tok") { description = "Toki Pona" }
        create("tr") { description = "Turkish" }
        create("tt") { description = "Tatar" }
        create("twq") { description = "Tasawaq" }
        create("tzm") { description = "Central Atlas Tamazight" }
        create("ug") { description = "Uyghur" }
        create("uk") { description = "Ukrainian" }
        create("ur") { description = "Urdu" }
        create("b+uz+Arab") { description = "Uzbek (Arabic)" }
        create("b+uz+Cyrl") { description = "Uzbek (Cyrillic)" }
        create("b+uz+Latn") { description = "Uzbek (Latin)" }
        create("b+vai+Latn") { description = "Vai (Latin)" }
        create("b+vai+Vaii") { description = "Vai (Vai)" }
        create("vec") { description = "Venetian" }
        create("vi") { description = "Vietnamese" }
        create("vmw") { description = "Makhuwa" }
        create("vun") { description = "Vunjo" }
        create("wae") { description = "Walser" }
        create("wo") { description = "Wolof" }
        create("xh") { description = "Xhosa" }
        create("xnr") { description = "Kangri" }
        create("xog") { description = "Soga" }
        create("yav") { description = "Yangben" }
        create("yi") { description = "Yiddish" } // alias to "ji" (API 26)
        create("yo") { description = "Yoruba" }
        create("yrl") { description = "Nheengatu" }
        create("b+yue+Hans") { description = "Cantonese (Simplified Han)" }
        create("b+yue+Hant") { description = "Cantonese (Traditional Han)" }
        create("za") { description = "Zhuang" }
        create("zgh") { description = "Standard Moroccan Tamazight" }
        create("b+zh+Hans") { description = "Chinese (Simplified Han)" }
        create("b+zh+Hant") { description = "Chinese (Traditional Han)" }
        create("zu") { description = "Zulu" }
    }
}
